# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

project_name: pushover-cli

before:
  hooks:
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  -
    binary: pushover-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - '6'
      - '7'
archives:
  -
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: amd64
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

universal_binaries:
  - replace: true

snapcrafts:
  -
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    publish: true
    summary: Unofficial CLI to send messages with pushover.net.
    description: Go based command line tool for message sending over pushover.net without any additional dependencies.
    grade: stable
    confinement: strict
    apps:
      pushover-cli:
        plugs: ["network"]

signs:
  -
    artifacts: checksum
    cmd: gpg
    args: ["-u", "A6349E78C6E207654029D63D684AF415E326EE40", "--output", "${signature}", "--detach-sign", "${artifact}"]

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
